### ISSUE TITLE
TypeError: 'object' object is not subscriptable

### ISSUE THREAD

**Issue by lucyb** [jkarres/enex2org#1]
I think this tool is excellent and exactly what I need to be able to move away from Evernote. I have successfully used it on individual notes. However, I get an error when using it on notebooks.

I've exported a notebook (with multiple notes) using Evernote 6.4 on Windows. I was initially using Evernote 5.6 (I think) and that also had the same issue. I've tried running the files through dos2unix, so I don't think it's a line-endings problem.

Do you know why this is happening?
```
Traceback (most recent call last):
  File "enex2org.py", line 172, in <module>
    run(args.input, args.output_dir, args.separate or [])
  File "enex2org.py", line 158, in run
    note.write(outfile, outpath)
  File "enex2org.py", line 91, in write
    outfile.write(enml.note2org(self))
  File "/home/lucy/Code/enex2org/enml.py", line 199, in note2org
    process_elt(root, rv)
  File "/home/lucy/Code/enex2org/enml.py", line 187, in process_elt
    process_elt(c, rv)
  File "/home/lucy/Code/enex2org/enml.py", line 178, in process_elt
    with tag2contextmgr.get(elt.tag, default)(rv, elt, note):
  File "/usr/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/home/lucy/Code/enex2org/enml.py", line 112, in add_newline
    if rv and rv[-1] and rv[-1][-1] != '\n':
TypeError: 'object' object is not subscriptable
```

**Comment by jkarres** [comment]
I'm glad it's helpful to you.

I think what's probably going on is that on line 112 rv[-1] is one of the objects defined on 41 (INDENT, DEDENT, etc).  I'll have to think about why that's happening, but for a quick fix, try changing line 112 from

    if rv and rv[-1] and rv[-1][-1] != '\n':

to

    if rv and type(rv[-1]) is str and rv[-1] and rv[-1][-1] != '\n':

Please let me know if that gets it working.

**Comment by lucyb** [comment]
Fantastic. Yes, that has done the job. 

Thank you.
